# Data Collection

### Notebook Summary

In [1]:
import pandas as pd

In [2]:
def read_and_concat_csv(filepath, quantity):
    temp_df_A = pd.DataFrame()
    for x in range(quantity):
        temp_df_B = pd.read_csv(f'{filepath}{x+1}.csv')
        temp_df_A = pd.concat([temp_df_A, temp_df_B])
    return temp_df_A

In [3]:
daily_2016_standard = read_and_concat_csv(
    '../data/batters_2016_daily/batters_2016_daily_standard', 6)
daily_2016_advanced = read_and_concat_csv(
    '../data/batters_2016_daily/batters_2016_daily_advanced', 6)
daily_2016_battedballs = read_and_concat_csv(
    '../data/batters_2016_daily/batters_2016_daily_battedballs', 6)

In [4]:
daily_2016 = daily_2016_standard.merge(daily_2016_advanced)
daily_2016 = daily_2016.merge(daily_2016_battedballs)

In [5]:
daily_2017_standard = read_and_concat_csv(
    '../data/batters_2017_daily/batters_2017_daily_standard', 6)
daily_2017_advanced = read_and_concat_csv(
    '../data/batters_2017_daily/batters_2017_daily_advanced', 6)
daily_2017_battedballs = read_and_concat_csv(
    '../data/batters_2017_daily/batters_2017_daily_battedballs', 6)

In [6]:
daily_2017 = daily_2017_standard.merge(daily_2017_advanced)
daily_2017 = daily_2017.merge(daily_2017_battedballs)

In [7]:
daily_2018_standard = read_and_concat_csv(
    '../data/batters_2018_daily/batters_2018_daily_standard', 6)
daily_2018_advanced = read_and_concat_csv(
    '../data/batters_2018_daily/batters_2018_daily_advanced', 6)
daily_2018_battedballs = read_and_concat_csv(
    '../data/batters_2018_daily/batters_2018_daily_battedballs', 6)

In [8]:
daily_2018 = daily_2018_standard.merge(daily_2018_advanced)
daily_2018 = daily_2018.merge(daily_2018_battedballs)

In [9]:
daily_2019_standard = read_and_concat_csv(
    '../data/batters_2019_daily/batters_2019_daily_standard', 2)
daily_2019_advanced = read_and_concat_csv(
    '../data/batters_2019_daily/batters_2019_daily_advanced', 2)
daily_2019_battedballs = read_and_concat_csv(
    '../data/batters_2019_daily/batters_2019_daily_battedballs', 2)

In [10]:
daily_2019 = daily_2019_standard.merge(daily_2019_advanced)
daily_2019 = daily_2019.merge(daily_2019_battedballs)

---
### Exporting

In [11]:
# daily_2016.to_csv('../data/batters_2016_daily_master.csv',
#                   index=False)
# daily_2017.to_csv('../data/batters_2017_daily_master.csv',
#                   index=False)
# daily_2018.to_csv('../data/batters_2018_daily_master.csv',
#                   index=False)
# daily_2019.to_csv('../data/batters_2019_daily_master.csv',
#                   index=False)

In [13]:
daily_2018[daily_2018.duplicated()]

,Date,Name,Tm,G,PA,AB,H,1B,2B,3B,...,IFFB%,HR/FB,IFH%,BUH%,Pull%,Cent%,Oppo%,Soft%,Med%,Hard%
12279,2018-05-12,Jace Peterson,BAL,1,3,2,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
12280,2018-05-12,Jace Peterson,BAL,1,3,2,0,0,0,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
12283,2018-05-12,Jace Peterson,BAL,1,3,2,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
12284,2018-05-12,Jace Peterson,BAL,1,3,2,0,0,0,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
16576,2018-05-28,Dansby Swanson,ATL,1,4,4,0,0,0,0,...,0.0,0.0,0.0,0.0,0.5,0.0,0.5,0.0,1.0,0.0
16577,2018-05-28,Dansby Swanson,ATL,1,4,4,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.5,0.5
16578,2018-05-28,Dansby Swanson,ATL,1,4,4,0,0,0,0,...,0.0,0.0,0.0,0.0,0.5,0.0,0.5,0.0,1.0,0.0
16579,2018-05-28,Dansby Swanson,ATL,1,4,4,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.5,0.5
16580,2018-05-28,Dansby Swanson,ATL,1,4,4,0,0,0,0,...,0.0,0.0,0.0,0.0,0.5,0.0,0.5,0.0,1.0,0.0
16581,2018-05-28,Dansby Swanson,ATL,1,4,4,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.5,0.5
28672,2018-07-09,Jesmuel Valentin,PHI,1,1,1,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28673,2018-07-09,Jesmuel Valentin,PHI,1,1,1,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28674,2018-07-09,Jesmuel Valentin,PHI,1,1,1,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28675,2018-07-09,Jesmuel Valentin,PHI,1,1,1,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28676,2018-07-09,Jesmuel Valentin,PHI,1,1,1,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28677,2018-07-09,Jesmuel Valentin,PHI,1,1,1,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28678,2018-07-09,Jesmuel Valentin,PHI,1,1,1,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35965,2018-08-07,Matt Adams,WSN,1,1,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35967,2018-08-07,Matt Adams,WSN,1,1,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35969,2018-08-07,Matt Adams,WSN,1,1,1,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35971,2018-08-07,Matt Adams,WSN,1,1,1,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45945,2018-09-11,Aaron Altherr,PHI,1,1,1,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45946,2018-09-11,Aaron Altherr,PHI,1,1,1,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45947,2018-09-11,Aaron Altherr,PHI,1,1,1,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45948,2018-09-11,Aaron Altherr,PHI,1,1,1,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45949,2018-09-11,Aaron Altherr,PHI,1,1,1,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45950,2018-09-11,Aaron Altherr,PHI,1,1,1,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45951,2018-09-11,Aaron Altherr,PHI,1,1,1,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45961,2018-09-11,Michael A. Taylor,WSN,1,1,1,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
45962,2018-09-11,Michael A. Taylor,WSN,1,1,1,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
45963,2018-09-11,Michael A. Taylor,WSN,1,1,1,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
45964,2018-09-11,Michael A. Taylor,WSN,1,1,1,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
45965,2018-09-11,Michael A. Taylor,WSN,1,1,1,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
45966,2018-09-11,Michael A. Taylor,WSN,1,1,1,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0

In [14]:
daily_2018.playerId.value_counts()

5930     174
16252    166
4949     166
11493    166
11579    165
5361     164
4922     164
2396     163
10556    163
11602    163
6609     162
18289    162
15998    162
16376    161
12916    160
11281    160
15149    160
6885     160
14344    160
11737    159
12979    159
13510    159
15172    159
9218     158
12533    158
12144    158
17678    157
14274    157
12564    157
16556    157
        ...
19206      1
18854      1
18694      1
6986       1
17470      1
4971       1
7146       1
13211      1
8173       1
13284      1
13188      1
13424      1
9266       1
16793      1
10925      1
11801      1
17496      1
17432      1
15570      1
10637      1
11632      1
19361      1
10534      1
5401       1
2882       1
14391      1
10123      1
3950       1
15068      1
5257       1
Name: playerId, Length: 992, dtype: int64

In [15]:
daily_2018_standard[daily_2018_standard.duplicated()]

,Date,Name,Tm,G,PA,AB,H,1B,2B,3B,...,IBB,SO,HBP,SF,SH,GDP,SB,CS,AVG,playerId
7805,2018-05-28,Dansby Swanson,ATL,1,4,4,0,0,0,0,...,0,2,0,0,0,0,0,0,0.0,18314
2488,2018-07-09,Jesmuel Valentin,PHI,1,1,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0.0,14548
3017,2018-09-11,Aaron Altherr,PHI,1,1,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0.0,11270
3197,2018-09-11,Michael A. Taylor,WSN,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0.0,11489

In [18]:
daily_2018_standard[daily_2018_standard.playerId == 16252]

,Date,Name,Tm,G,PA,AB,H,1B,2B,3B,...,IBB,SO,HBP,SF,SH,GDP,SB,CS,AVG,playerId
286,2018-03-30,Trea Turner,WSN,1,4,3,0,0,0,0,...,0,0,0,0,0,0,0,0,0.000000,16252
809,2018-03-31,Trea Turner,WSN,1,5,4,2,1,0,0,...,0,0,0,0,0,0,0,0,0.500000,16252
975,2018-04-01,Trea Turner,WSN,1,5,4,1,1,0,0,...,0,1,0,0,0,0,1,0,0.250000,16252
1210,2018-04-02,Trea Turner,WSN,1,6,5,1,1,0,0,...,0,1,0,0,0,0,0,0,0.200000,16252
1390,2018-04-03,Trea Turner,WSN,1,5,4,1,1,0,0,...,0,1,0,0,0,0,2,0,0.250000,16252
1732,2018-04-04,Trea Turner,WSN,1,4,3,1,1,0,0,...,0,1,0,0,0,0,0,0,0.333333,16252
1864,2018-04-05,Trea Turner,WSN,1,3,3,0,0,0,0,...,0,3,0,0,0,0,0,0,0.000000,16252
2441,2018-04-07,Trea Turner,WSN,1,4,3,1,1,0,0,...,0,0,0,0,0,0,1,0,0.333333,16252
2859,2018-04-08,Trea Turner,WSN,1,6,5,1,1,0,0,...,1,0,0,0,0,0,1,0,0.200000,16252
3063,2018-04-09,Trea Turner,WSN,1,4,3,0,0,0,0,...,0,1,0,0,0,0,0,0,0.000000,16252
3438,2018-04-10,Trea Turner,WSN,1,4,4,0,0,0,0,...,0,2,0,0,0,0,0,0,0.000000,16252
3641,2018-04-11,Trea Turner,WSN,1,5,5,2,2,0,0,...,0,1,0,0,0,1,0,0,0.400000,16252
3931,2018-04-12,Trea Turner,WSN,1,4,4,0,0,0,0,...,0,1,0,0,0,0,0,0,0.000000,16252
4119,2018-04-13,Trea Turner,WSN,1,4,3,1,0,1,0,...,0,1,0,0,0,0,0,0,0.333333,16252
4246,2018-04-14,Trea Turner,WSN,1,5,4,1,1,0,0,...,0,0,0,0,0,0,1,0,0.250000,16252
4672,2018-04-15,Trea Turner,WSN,1,5,2,0,0,0,0,...,0,1,0,0,0,0,0,0,0.000000,16252
4726,2018-04-16,Trea Turner,WSN,1,5,5,2,2,0,0,...,0,0,0,0,0,0,1,0,0.400000,16252
4893,2018-04-17,Trea Turner,WSN,1,5,4,3,1,2,0,...,0,0,0,0,0,0,1,0,0.750000,16252
5285,2018-04-18,Trea Turner,WSN,1,4,4,0,0,0,0,...,0,2,0,0,0,0,0,0,0.000000,16252
6005,2018-04-20,Trea Turner,WSN,1,5,5,2,1,1,0,...,0,0,0,0,0,0,0,0,0.400000,16252
6252,2018-04-21,Trea Turner,WSN,1,4,4,1,1,0,0,...,0,0,0,0,0,0,0,0,0.250000,16252
6342,2018-04-22,Trea Turner,WSN,1,5,5,0,0,0,0,...,0,2,0,0,0,0,0,0,0.000000,16252
6673,2018-04-23,Trea Turner,WSN,1,5,5,2,1,0,1,...,0,2,0,0,0,0,1,0,0.400000,16252
6924,2018-04-24,Trea Turner,WSN,1,4,4,0,0,0,0,...,0,0,0,0,0,0,0,0,0.000000,16252
7292,2018-04-25,Trea Turner,WSN,1,6,6,5,4,1,0,...,0,0,0,0,0,0,1,0,0.833333,16252
7738,2018-04-27,Trea Turner,WSN,1,5,5,2,2,0,0,...,0,1,0,0,0,0,0,0,0.400000,16252
8103,2018-04-28,Trea Turner,WSN,1,5,4,0,0,0,0,...,0,2,0,0,0,1,1,0,0.000000,16252
8478,2018-04-29,Trea Turner,WSN,1,4,2,1,1,0,0,...,0,1,0,0,0,0,1,0,0.500000,16252
8680,2018-04-30,Trea Turner,WSN,1,4,4,3,2,1,0,...,0,0,0,0,0,0,0,0,0.750000,16252
324,2018-05-01,Trea Turner,WSN,1,4,3,1,0,1,0,...,0,0,0,0,0,0,0,1,0.333333,16252
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7534,2018-08-28,Trea Turner,WSN,1,4,4,0,0,0,0,...,0,1,0,0,0,0,0,0,0.000000,16252
7849,2018-08-29,Trea Turner,WSN,1,5,5,1,0,0,0,...,0,3,0,0,0,0,0,0,0.200000,16252
8420,2018-08-31,Trea Turner,WSN,1,5,4,3,2,1,0,...,0,0,0,0,0,0,1,0,0.750000,16252
138,2018-09-01,Trea Turner,WSN,1,4,4,2,2,0,0,...,0,0,0,0,0,0,1,0,0.500000,16252
522,2018-09-02,Trea Turner,WSN,1,5,5,1,1,0,0,...,0,2,0,0,0,0,0,0,0.200000,16252
916,2018-09-03,Trea Turner,WSN,1,6,5,1,0,0,0,...,0,0,0,0,0,0,0,0,0.200000,16252
1105,2018-09-04,Trea Turner,WSN,1,5,3,2,2,0,0,...,0,0,0,0,0,0,0,0,0.666667,16252
1546,2018-09-05,Trea Turner,WSN,1,5,5,1,1,0,0,...,0,0,0,0,0,0,0,0,0.200000,16252
1685,2018-09-06,Trea Turner,WSN,1,5,4,1,1,0,0,...,0,3,0,0,0,0,0,0,0.250000,16252
2056,2018-09-08,Trea Turner,WSN,1,5,5,1,1,0,0,...,0,1,0,0,0,0,0,0,0.200000,16252
2181,2018-09-08,Trea Turner,WSN,1,5,3,0,0,0,0,...,0,0,0,0,0,0,2,0,0.000000,16252
3045,2018-09-11,Trea Turner,WSN,1,5,4,0,0,0,0,...,0,2,0,0,0,1,0,0,0.000000,16252
3109,2018-09-11,Trea Turner,WSN,1,5,4,1,0,1,0,...,0,0,0,0,0,1,0,0,0.250000,16252
3585,2018-09-12,Trea Turner,WSN,1,4,4,1,1,0,0,...,0,0,0,0,0,0,0,0,0.250000,16252
3664,2018-09-13,Trea Turner,WSN,1,5,5,1,0,1,0,...,0,2,0,0,0,0,1,0,0.200000,16252
3838,2018-09-14,Trea Turner,WSN,1,5,5,2,1,1,0,...,0,0,0,0,0,0,1,0,0.400000,16252
4241,2018-09-15,Trea Turner,WSN,1,6,5,1,1,0,0,...,0,2,0,0,0,0,0,1,0.200000,16252
4756,2018-09-16,Trea Turner,WSN,1,5,5,1,1,0,0,...,0,1,0,0,0,0,0,0,0.200000,16252
4861,2018-09-17,Trea Turner,WSN,1,4,4,1,1,0,0,...,0,1,0,0,0,0,0,0,0.250000,16252
5240,2018-09-18,Trea Turner,WSN,1,5,4,2,2,0,0,...,0,1,1,0,0,1,1,0,0.500000,16252
5784,2018-09-20,Trea Turner,WSN,1,6,4,1,1,0,0,...,0,0,0,0,0,0,0,0,0.250000,16252
6180,2018-09-21,Trea Turner,WSN,1,4,4,1,0,1,0,...,0,1,0,0,0,0,0,0,0.250000,16252
6311,2018-09-22,Trea Turner,WSN,1,4,3,2,0,1,0,...,0,1,0,0,0,0,1,0,0.666667,16252
6794,2018-09-23,Trea Turner,WSN,1,5,2,2,1,1,0,...,0,0,0,0,0,0,1,0,1.000000,16252
7223,2018-09-24,Trea Turner,WSN,1,5,5,2,1,1,0,...,0,1,0,0,0,0,1,0,0.400000,16252
7474,2018-09-25,Trea Turner,WSN,1,5,5,0,0,0,0,...,0,2,0,0,0,1,0,0,0.000000,16252
7622,2018-09-26,Trea Turner,WSN,1,5,3,0,0,0,0,...,0,0,0,0,0,0,0,0,0.000000,16252
8294,2018-09-28,Trea Turner,WSN,1,5,5,1,0,0,1,...,0,0,0,0,0,0,0,0,0.200000,16252
8815,2018-09-29,Trea Turner,WSN,1,6,6,3,2,0,0,...,0,1,0,0,0,0,0,0,0.500000,16252
9208,2018-09-30,Trea Turner,WSN,1,4,4,1,1,0,0,...,0,1,0,0,0,1,0,0,0.250000,16252