In [1]:
import pandas as pd

In [3]:
batters_2018_standard = pd.read_csv('../data/fangraphs/batters_2018_standard.csv')

In [11]:
batters_2018_standard.groupby('Team')['Name'].count()

Team
Angels          5
Astros          5
Athletics       5
Blue Jays       3
Braves          6
Brewers         6
Cardinals       5
Cubs            5
Diamondbacks    5
Dodgers         2
Giants          4
Indians         4
Mariners        6
Marlins         3
Mets            3
Nationals       2
Orioles         3
Padres          4
Phillies        5
Pirates         2
Rangers         4
Rays            2
Red Sox         5
Reds            5
Rockies         4
Royals          4
Tigers          2
Twins           5
White Sox       5
Yankees         3
Name: Name, dtype: int64

In [12]:
batters_2018_standard[batters_2018_standard['Team']=='Cardinals']

,Name,Team,G,AB,PA,H,1B,2B,3B,HR,...,IBB,SO,HBP,SF,SH,GDP,SB,CS,AVG,playerid
10,Jose Martinez,Cardinals,152,534,590,163,116,30,0,17,...,0,104,2,3,2,15,0,3,0.305,7996
25,Paul Goldschmidt,Cardinals,158,593,690,172,99,35,5,33,...,11,173,6,0,0,7,7,4,0.290,9218
35,Marcell Ozuna,Cardinals,148,582,628,163,122,16,2,23,...,2,110,3,4,0,10,3,0,0.280,10324
58,Yadier Molina,Cardinals,123,459,503,120,80,20,0,20,...,0,66,9,6,0,15,4,3,0.261,7007
64,Matt Carpenter,Cardinals,156,564,677,145,67,42,0,36,...,17,158,6,4,0,0,4,1,0.257,8090

In [13]:
df2017 = pd.read_csv('../data/fangraphs/batters_2017_standard.csv')

In [16]:
df2017[df2017['Team'] == 'Cardinals']

,Name,Team,G,AB,PA,H,1B,2B,3B,HR,...,IBB,SO,HBP,SF,SH,GDP,SB,CS,AVG,playerid
32,Marcell Ozuna,Cardinals,159,613,679,191,122,30,2,37,...,4,144,0,2,0,18,1,3,0.312,10324
34,Jose Martinez,Cardinals,106,272,307,84,56,13,1,14,...,2,60,0,2,1,9,4,0,0.309,7996
57,Paul Goldschmidt,Cardinals,155,558,665,166,93,34,3,36,...,15,147,8,4,0,14,18,5,0.297,9218
87,Paul DeJong,Cardinals,108,417,443,119,67,26,1,25,...,1,124,4,1,0,8,1,0,0.285,18015
88,Kolten Wong,Cardinals,108,354,411,101,67,27,3,4,...,11,60,12,3,1,4,8,2,0.285,12532
119,Yadier Molina,Cardinals,136,501,543,137,91,27,1,18,...,4,74,4,9,1,14,9,4,0.273,7007
127,Jedd Gyorko,Cardinals,125,426,481,116,73,21,2,20,...,1,105,1,7,0,12,6,2,0.272,10816
161,Dexter Fowler,Cardinals,118,420,491,111,62,22,9,18,...,6,101,4,4,0,10,7,3,0.264,4062
168,Adam Wainwright,Cardinals,26,42,50,11,7,2,0,2,...,0,15,0,0,7,2,0,0,0.262,2233
252,Matt Carpenter,Cardinals,145,497,622,120,64,31,2,23,...,4,125,9,5,2,5,2,1,0.241,8090
284,Matt Wieters,Cardinals,123,422,465,95,65,20,0,10,...,4,94,1,4,0,14,1,0,0.225,4298
427,Brett Cecil,Cardinals,73,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.000,2660
463,Andrew Miller,Cardinals,57,1,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0.000,6785
537,John Brebbia,Cardinals,50,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.000,12777
568,John Gant,Cardinals,7,3,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.000,13684
572,Dominic Leone,Cardinals,65,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.000,13763
597,Tyler Webb,Cardinals,9,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.000,14974
598,Giovanny Gallegos,Cardinals,16,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.000,14986
631,Jack Flaherty,Cardinals,6,6,6,0,0,0,0,0,...,0,2,0,0,0,0,0,0,0.000,17479

In [6]:
batters_2018_standard.head()

,Name,Team,G,AB,PA,H,1B,2B,3B,HR,...,IBB,SO,HBP,SF,SH,GDP,SB,CS,AVG,playerid
0,Mookie Betts,Red Sox,136,520,614,180,96,47,5,32,...,8,91,8,5,0,5,30,6,0.346,13611
1,J.D. Martinez,Red Sox,150,569,649,188,106,37,2,43,...,11,146,4,7,0,19,6,1,0.330,6184
2,Christian Yelich,Brewers,147,574,651,187,110,34,7,36,...,2,135,7,2,0,14,22,4,0.326,11477
3,Jose Altuve,Astros,137,534,599,169,125,29,2,13,...,4,79,6,1,3,17,17,4,0.316,5417
4,Mike Trout,Angels,140,471,608,147,80,24,4,39,...,25,124,10,4,0,5,24,2,0.312,10155

In [17]:
daily_2018 = pd.read_csv('../data/fangraphs/batters_2018_daily_standard.csv')

In [18]:
daily_2018.shape

(360, 24)

In [19]:
daily_2018

,Season,Name,Tm,G,PA,AB,H,1B,2B,3B,...,IBB,SO,HBP,SF,SH,GDP,SB,CS,AVG,playerId
0,2018,Victor Martinez,DET,133,508,467,117,87,21,0,...,4,49,2,7,0,19,0,0,0.250535,393
1,2018,Adrian Beltre,TEX,119,481,433,118,79,23,1,...,2,96,6,8,0,13,1,0,0.272517,639
2,2018,Todd Frazier,NYM,115,472,408,87,51,18,0,...,1,112,8,8,0,10,9,4,0.213235,785
3,2018,Albert Pujols,LAA,117,498,465,114,75,20,0,...,3,65,2,3,0,12,1,0,0.245161,1177
4,2018,Wilson Ramos,2 Tms,110,416,382,117,79,22,1,...,2,80,0,2,0,20,0,0,0.306283,1433
5,2018,Jose Reyes,NYM,102,251,228,43,24,12,3,...,1,39,0,0,1,5,5,2,0.188596,1736
6,2018,Joe Mauer,MIN,127,543,486,137,103,27,1,...,5,86,2,3,1,9,0,1,0.281893,1857
7,2018,Jose Bautista,3 Tms,122,399,325,66,35,18,0,...,2,111,6,1,0,2,4,3,0.203077,1887
8,2018,David Peralta,ARI,146,614,560,164,104,25,5,...,4,124,4,2,0,14,4,0,0.292857,2136
9,2018,Edwin Encarnacion,CLE,137,579,500,123,74,16,1,...,2,132,8,7,0,14,3,0,0.246000,2151
10,2018,Carlos Santana,PHI,161,679,560,128,74,28,2,...,6,93,1,8,0,12,2,1,0.228571,2396
11,2018,Nelson Cruz,SEA,144,591,519,133,77,18,1,...,5,122,14,3,0,15,1,0,0.256262,2434
12,2018,Lucas Duda,2 Tms,105,367,328,79,50,14,1,...,2,102,8,3,0,5,1,0,0.240854,2502
13,2018,Yonder Alonso,CLE,142,574,516,129,87,19,0,...,1,123,2,5,0,10,0,0,0.250000,2530
14,2018,Zack Cozart,LAA,58,253,224,49,29,13,2,...,0,42,7,3,0,7,0,0,0.218750,2616
15,2018,Brandon Guyer,CLE,90,221,194,40,22,11,0,...,0,48,11,0,1,5,1,1,0.206186,2636
16,2018,Manny Pina,MIL,95,337,306,77,53,13,2,...,3,62,5,4,1,13,2,0,0.251634,2829
17,2018,Roberto Perez,CLE,62,210,179,30,18,9,1,...,0,70,1,2,7,6,1,0,0.167598,2900
18,2018,Tommy Pham,2 Tms,136,570,494,136,91,18,6,...,2,140,6,3,0,18,15,7,0.275304,2967
19,2018,Mitch Moreland,BOS,120,459,404,99,57,23,4,...,2,102,0,5,0,12,2,0,0.245050,3086
20,2018,Gregor Blanco,SFG,66,203,189,41,29,7,3,...,0,58,0,1,1,2,6,2,0.216931,3123
21,2018,Robinson Chirinos,TEX,111,426,360,80,46,15,1,...,0,140,19,2,0,7,2,0,0.222222,3142
22,2018,Shin-Soo Choo,TEX,146,665,560,148,96,30,1,...,2,156,10,2,1,11,6,1,0.264286,3174
23,2018,Robinson Cano,SEA,80,348,310,94,62,22,0,...,2,47,4,2,0,9,0,0,0.303226,3269
24,2018,Charlie Culberson,ATL,112,322,296,80,48,18,2,...,5,85,4,1,0,5,4,2,0.270270,3298
25,2018,Martin Prado,MIA,54,209,197,48,38,9,0,...,0,35,1,0,0,5,1,1,0.243655,3312
26,2018,Matt Joyce,OAK,80,246,207,43,27,9,0,...,2,53,1,2,1,3,0,2,0.207729,3353
27,2018,Nick Hundley,SFG,96,305,282,68,43,13,2,...,2,85,1,0,0,8,2,1,0.241135,3376
28,2018,Ryan Braun,MIL,125,447,405,103,57,25,1,...,5,85,2,3,0,8,11,5,0.254321,3410
29,2018,Jeff Mathis,ARI,67,218,195,39,28,9,1,...,1,66,0,2,1,7,0,0,0.200000,3448
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
330,2018,Yairo Munoz,STL,103,329,293,81,57,16,0,...,7,71,4,2,0,3,5,6,0.276451,16313
331,2018,Michael Conforto,NYM,153,638,543,132,78,25,1,...,8,159,7,4,0,10,3,4,0.243094,16376
332,2018,Rhys Hoskins,PHI,153,660,558,137,65,38,0,...,2,150,9,5,0,7,5,3,0.245520,16472
333,2018,Kyle Schwarber,CHC,136,510,428,102,59,14,3,...,20,140,1,2,1,6,4,3,0.238318,16478
334,2018,Matt Chapman,OAK,145,616,547,152,80,42,6,...,0,146,9,2,0,18,1,2,0.277879,16505
335,2018,Isiah Kiner-Falefa,TEX,106,396,356,93,69,18,2,...,1,62,6,1,5,14,7,5,0.261236,16512
336,2018,Ozzie Albies,ATL,157,684,639,167,98,40,5,...,0,116,5,3,1,9,14,3,0.261346,16556
337,2018,Greg Allen,CLE,85,291,265,68,52,11,3,...,1,58,7,1,4,5,21,4,0.256604,16623
338,2018,Colin Moran,PIT,144,465,415,115,84,19,1,...,4,82,4,7,0,6,0,2,0.277108,16909
339,2018,Gleyber Torres,NYY,122,484,431,117,76,16,1,...,3,122,5,5,1,8,6,2,0.271462,16997
340,2018,Dustin Fowler,OAK,65,203,192,43,32,3,2,...,0,47,1,2,0,2,6,4,0.223958,17098
341,2018,Yoan Moncada,CHW,149,650,578,136,81,32,6,...,1,217,1,2,2,4,12,6,0.235294,17232
342,2018,Rafael Devers,BOS,120,490,450,108,63,24,0,...,6,121,0,2,0,9,5,2,0.240000,17350
343,2018,J.T. Riddle,MIA,96,332,308,71,48,10,4,...,1,67,0,1,3,4,0,3,0.230519,17642
344,2018,Alex Bregman,HOU,157,705,594,170,87,51,1,...,2,85,12,3,0,15,10,4,0.286195,17678
345,2018,Andrew Benintendi,BOS,147,661,579,168,105,41,6,...,1,106,2,7,2,9,21,3,0.290155,17901
346,2018,Ian Happ,CHC,135,462,387,90,54,19,2,...,9,167,3,2,0,6,8,4,0.232558,17919
347,2018,Cedric Mullins II,BAL,44,191,170,40,27,9,0,...,0,37,2,0,2,1,2,3,0.235294,17929
348,2018,Scott Kingery,PHI,140,484,452,102,69,23,2,...,1,126,3,5,0,2,10,3,0.225664,17975
349,2018,David Fletcher,LAA,79,307,284,78,57,18,2,...,0,34,3,2,3,7,3,0,0.274648,17992
350,2018,Paul DeJong,STL,114,490,436,105,60,25,1,...,2,123,12,5,0,6,1,1,0.240826,18015
351,2018,Harrison Bader,STL,129,427,379,100,66,20,2,...,3,125,11,4,2,1,15,3,0.263852,18030
352,2018,Brian Anderson,MIA,156,670,590,161,112,34,4,...,2,129,16,2,0,18,2,4,0.272881,18289
353,2018,Dansby Swanson,ATL,134,533,478,114,71,25,4,...,15,122,2,3,6,5,10,4,0.238494,18314
354,2018,Ronald Acuna Jr.,ATL,111,487,433,127,71,26,4,...,2,123,6,3,0,4,16,5,0.293303,18401
355,2018,Guillermo Heredia,SEA,107,337,292,69,49,14,1,...,0,52,4,2,7,4,2,4,0.236301,18721
356,2018,Yuli Gurriel,HOU,136,573,537,156,109,33,1,...,0,63,6,7,0,22,5,1,0.290503,19198
357,2018,Lourdes Gurriel Jr.,TOR,64,263,249,70,51,8,0,...,1,59,2,2,1,2,1,2,0.281124,19238
358,2018,Shohei Ohtani,LAA,104,367,326,93,48,21,2,...,2,102,2,1,0,2,10,4,0.285276,19755
359,2018,Juan Soto,WSN,116,494,414,121,73,25,1,...,10,99,0,0,1,9,5,2,0.292271,20123

In [22]:
daily_2018.Tm.value_counts()

2 Tms    36
ARI      13
BOS      13
HOU      13
CHC      13
CLE      12
SFG      12
SDP      12
DET      12
CHW      11
TOR      11
COL      11
WSN      11
NYY      11
TEX      11
STL      11
MIL      11
OAK      11
PHI      10
LAA      10
PIT      10
LAD      10
MIN      10
TBR      10
ATL      10
SEA      10
BAL       9
CIN       9
NYM       9
KCR       8
MIA       8
3 Tms     2
Name: Tm, dtype: int64

In [26]:
daily_2018.shape

(360, 24)

In [23]:
daily_2019 = pd.read_csv('../data/fangraphs/batters_2019_daily_standard.csv')

In [24]:
daily_2019.shape

(7701, 24)

In [25]:
daily_2019.head()

,Date,Name,Tm,G,PA,AB,H,1B,2B,3B,...,IBB,SO,HBP,SF,SH,GDP,SB,CS,AVG,playerId
0,2019-03-20,Jay Bruce,SEA,1,5,4,1,1,0,0,...,0,2,1,0,0,0,0,0,0.25,9892
1,2019-03-20,Jurickson Profar,OAK,1,4,4,1,0,1,0,...,0,1,0,0,0,0,0,0,0.25,10815
2,2019-03-20,Omar Narvaez,SEA,1,4,3,0,0,0,0,...,0,1,0,0,0,0,0,0,0.00,13338
3,2019-03-20,Ichiro Suzuki,SEA,1,2,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0.00,1101
4,2019-03-20,Daniel Vogelbach,SEA,1,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0.00,14130